#!/bin/bash
#
# /etc/rc.d/init.d/kafka_exporter
#
# chkconfig: 2345 80 80
#

# Source function library.
. /etc/init.d/functions

case "$1" in
start)
    echo "start kafka_exporter"
    /opt/exporter/kafka_exporter --kafka.server=kafka_ip:kafka_port --web.listen-address=":9308" &
	;;
stop)
    echo "stop kafka_exporter"
    ps aux|grep /opt/exporter/kafka_exporter|grep -v grep|awk '{print $2}'|xargs kill -9
    ;;
restart)
    $0 stop
    $0 start
    ;;
esac


