#!/bin/bash
#
# /etc/rc.d/init.d/mysqld_exporter
#
# chkconfig: 2345 80 80
#

# Source function library.
. /etc/init.d/functions

case "$1" in
start)
    echo "start mysqld_exporter"
    /opt/exporter/mysqld_exporter --web.listen-address=0.0.0.0:9104 --config.my-cnf=/opt/exporter/3306.cnf &
	;;
stop)
    echo "stop mysqld_exporter"
    ps aux|grep /opt/exporter/mysqld_exporter|grep -v grep|awk '{print $2}'|xargs kill -9
    ;;
restart)
    $0 stop
    $0 start
    ;;
esac

