#!/bin/bash
#
# /etc/rc.d/init.d/redis_exporter
#
# chkconfig: 2345 80 80
#

# Source function library.
. /etc/init.d/functions

case "$1" in
start)
    echo "start redis_exporter"
    /opt/exporter/redis_exporter -redis.addr redis_addr -redis.password reids_pass &
    ;;
stop)
    echo "stop redis_exporter"
    ps aux|grep /opt/exporter/redis_exporter|grep -v grep|awk '{print $2}'|xargs kill -9
    ;;
restart)
    $0 stop
    $0 start
    ;;
esac
