#!/bin/bash
#
# /etc/rc.d/init.d/zabbix_agentd
#
# chkconfig: 2345 80 80
#

# Source function library.
. /etc/init.d/functions

case "$1" in
start)
    echo "start zabbix_agentd"
    /usr/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf &
    ;;
stop)
    echo "stop zabbix_agentd"
    ps aux|grep /usr/sbin/zabbix_agentd|grep -v grep|awk '{print $2}'|xargs kill -9
    ;;
restart)
    $0 stop
    $0 start
    ;;
esac
