#!/bin/bash
#
# /etc/rc.d/init.d/node_exporter
#
# chkconfig: 2345 80 80
#

# Source function library.
. /etc/init.d/functions

case "$1" in
start)
    echo "start node_exporter"
    /opt/exporter/node_exporter --web.listen-address=0.0.0.0:9100 --collector.textfile.directory=/opt/exporter/key/ &
	;;
stop)
    echo "stop node_exporter"
    ps aux|grep /opt/exporter/node_exporter|grep -v grep|awk '{print $2}'|xargs kill -9
    ;;
restart)
    $0 stop
    $0 start
    ;;
esac

